baseURL = "http://www.learningrfordatascience.com/"
languageCode = "en-us"
title = "Learning R for Data Science"
theme = "hugo-journal"
#disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Ron Richardson"
    description = "Learning R for Data Science at Mercyhurst University"
    tagline = "Learning R for Data Science at Mercyhurst University"
    githubUsername = "rer145"
    twitterUsername = "rer145"
    linkedinUsername = "rer145"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[params.work]
  jobTitle = "Grad Student"
  company = "Mercyhurst University"
  companyUrl = "https://www.mercyhurst.edu/"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rricha67@lakers.mercyhurst.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rer145/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rer145/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rer145/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/rer145/"
    name = "stack-overflow"
    weight = 5
